//Default route
###
GET http://localhost:5000/



 //..........................................USER.......................................................//

//get all users
###
GET http://localhost:5000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyX0lkIjozOCwiRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJGdWxsTmFtZSI6ImFkbWluIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTk1ODMzOSwiaWF0IjoxNzQ5OTU0NzM5fQ.-1JYBG3WPSFDDMtNkAqnKmVPxOpFI9maZi3SaVhKbqs
//get user by Id
###
GET http://localhost:5000/api/users/2

//register a user
###
POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "Full_Name": "Ascah kepha",
    "Contact_Phone": "0706199668",
    "Email": "admin@gmail.com",
    "Confirmation_Code": "A1020",
    "Password": "admin"
}

//login a user
###
POST http://localhost:5000/api/auth/login
content-type: application/json

{  
    "Email": "admin@gmail.com",
    "Password": "admin"   
}

//Update user
###
PUT  http://localhost:5000/api/users/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyX0lkIjozNywiRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJGdWxsTmFtZSI6ImFkbWluIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTU2NTMzMywiaWF0IjoxNzQ5NTYxNzMzfQ.SM7AjjWQtn8sJxzXlCKUjn7ZRRR1ZHWpYk00FAbgoQw
content-type: application/json

{
    "Full_Name": "Ascah",
    "Contact_Phone": 12345678,
    "Email": "ascah@gmail.com",
    "Confirmation_Code": "A1020",
    "Password": "daniel123",
    "User_Type": "member"  
}
//delete user
### 
DELETE http://localhost:5000/api/users/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyX0lkIjozNywiRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJGdWxsTmFtZSI6ImFkbWluIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTU2NTMzMywiaWF0IjoxNzQ5NTYxNzMzfQ.SM7AjjWQtn8sJxzXlCKUjn7ZRRR1ZHWpYk00FAbgoQw

 // .......................................................state...............................................................//


 //get all states
###
GET http://localhost:5000/api/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZnVsbE5hbWUiOiJhZG1pbiIsInVzZXJUeXBlIjoiYWRtaW4iLCJleHAiOjE3NDkwNTA5NjksImlhdCI6MTc0OTA0NzM2OX0.7zUvcqkawulbvmWhkC8VsuzxI7N8zn75TUbIiMuj5sc


//get state by Id
###
GET http://localhost:5000/api/states/1
Authorization: 

//create state
###
POST http://localhost:5000/api/states
content-type: application/json
Authorization: 

{
    
    "State_Name": "Pumwani",
    "Code": "Nairobi 254"
    
}

//Update state
###
PUT  http://localhost:5000/api/states/1
content-type: application/json

{
    "State_Name": "Pumwani",
    "Code": "Nairobi 254"
}

//delete user
### 
DELETE http://localhost:5000/api/states/2
Authorization: 
  



//......................................................................CITY.........................................................................//


  //get all cities
###
GET http://localhost:5000/api/city
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZnVsbE5hbWUiOiJhZG1pbiIsInVzZXJUeXBlIjoiYWRtaW4iLCJleHAiOjE3NDkwNTA5NjksImlhdCI6MTc0OTA0NzM2OX0.7zUvcqkawulbvmWhkC8VsuzxI7N8zn75TUbIiMuj5sc


//get city by Id
###
GET http://localhost:5000/api/city/2

//create city
###
POST http://localhost:5000/api/city
content-type: application/json

{
    "City_Name": "Nai",
    "State_Id": 1  
}

//Update city
###
PUT  http://localhost:5000/api/city/3
content-type: application/json

{
    "City_Name": "Nai",
    "State_Id": 1
}

//delete city
### 
DELETE http://localhost:5000/api/city/3
  

  //......................................................................menu_Item.........................................................................//

//get all menu items
###
GET http://localhost:5000/api/menu_items
Authorization: <your_token>

//get menu item by Id  
### 
GET http://localhost:5000/api/menu_items/1

//create menu item
###
POST http://localhost:5000/api/menu_items
content-type: application/json

{
   "Menu_Name": "Pizza",
   "Restaurant_Id": 1,
   "Category_Id": 1,
   "Description": "pizza.jpg",
   "Ingredients": "hoho",
   "Price": 50.50,
   "Active": true
}

//update menu item
###
PUT http://localhost:5000/api/menu_items/1
content-type: application/json

{
   "Menu_Name": "Pizza",
   "Restaurant_Id": 1,
   "Category_Id": 1,
   "Description": "pizza.jpg",
   "Ingredients": "hoho",
   "Price": 50.50,
   "Active": true
}

//delete menu item
###
DELETE http://localhost:5000/api/menu_items/9

//.......................................................driver...............................................................//

//get all drivers
###
GET http://localhost:5000/api/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiZGFuaWVsIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTA1NDkzMCwiaWF0IjoxNzQ5MDUxMzMwfQ.u5e51kHHu6DK-SDQ2Imi0gApMITH6dY-Mq3KNLAATCM

//get driver by Id
###
GET http://localhost:5000/api/drivers/3

//create driver
###
POST http://localhost:5000/api/drivers
content-type: application/json

{
    "Car_Make": "Volvo",
    "Car_Model": "V40",
    "Car_Year": 2020,
    "User_Id": 1,
    "Online": true,
    "Delivering": false
}

//Update driver
###
PUT  http://localhost:5000/api/drivers/1
content-type: application/json

{
    "Car_Make": "Tx",
    "Car_Model": "Toyota",
    "Car_Year": 2020,
    "User_Id": 1,
    "Online": true,
    "Delivering": false
}

//delete driver
###
DELETE http://localhost:5000/api/drivers/3

//.......................................................address...............................................................//

//get all addresses
###
GET http://localhost:5000/api/addresses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiZGFuaWVsIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTA1NDkzMCwiaWF0IjoxNzQ5MDUxMzMwfQ.u5e51kHHu6DK-SDQ2Imi0gApMITH6dY-Mq3KNLAATCM

//get address by Id
###
GET http://localhost:5000/api/addresses/1

//create address
###
POST http://localhost:5000/api/addresses
content-type: application/json

{

    "Street_Address_1": "downtown123",
    "Street_Address_2":"Mumbai254" ,
    "Zip_Code": "ewDelhi120",
    "Delivery_Instructions":"get on time" ,
    "User_Id": 2,
    "City_Id": 2
}

//Update address
###
PUT  http://localhost:5000/api/addresses/1
content-type: application/json

{
    "Street_Address_1": "123 Main St",
    "Street_Address_2": "Apt 4B",
    "Zip_Code": "10001",
    "Delivery_Instructions": "Leave at front door",
    "User_Id": 3,
    "City_Id": 4
}

//delete address
###
DELETE http://localhost:5000/api/addresses/3


//.......................................................orders...............................................................//

//get all orders
###
GET http://localhost:5000/api/orders
Authorization: <your_token>

//get order by Id
###
GET http://localhost:5000/api/orders/1

//create order
###
POST http://localhost:5000/api/orders
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "today 11:30am",
    "Actual_Delivery_Time": "2025-06-09T11:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 35,
    "Driver_Id": 1,
    "Price": "500.0",
    "Discount": "20.5",
    "Final_Price": "485",
    "Comment": "Thank You",
    "items": [
        {
            "Menu_Item_Id": 1,
            "Quantity": 2,
            "Item_Price": "100",
            "Price": "150",
            "Comment": "Yummy"
        }
    ],
    "statuses": [
        {
            "Status_Catalog_Id": 1
        }
    ]
}

//update order
###
PUT http://localhost:5000/api/orders/1
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "today 12:30pm",
    "Actual_Delivery_Time": "2025-06-09T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 35,
    "Driver_Id": 1,
    "Price": "550.0",
    "Discount": "25.5",
    "Final_Price": "525",
    "Comment": "Updated delivery instructions",
    "items": [
        {
            "Menu_Item_Id": 1,
            "Quantity": 3,
            "Item_Price": "100",
            "Price": "200",
            "Comment": "Extra spicy"
        }
    ],
    "statuses": [
        {
            "Status_Catalog_Id": 2
        }
    ]
}

//delete order
###
DELETE http://localhost:5000/api/orders/1

//.......................................................order_menu...............................................................//

//get all order menu items
###
GET http://localhost:5000/api/order-menu-items
Authorization: <your_token>

//get order menu item by Id
###
GET http://localhost:5000/api/order-menu-items/4

//create order menu item
###
POST http://localhost:5000/api/order-menu-items
content-type: application/json

{
    "menu_Order_Id": 1,
    "Menu_Item_Id": 2,
    "Quantity": 2,
    "Item_Price":20.50,
    "Price": 1000,
    "Comment":"work hard"
}

//update order menu item
###
PUT http://localhost:5000/api/order-menu-items/1
content-type: application/json

{
    "menu_Order_Id": 1,
    "Menu_Item_Id": 2,
    "Quantity": 2,
    "Item_Price":20.50,
    "Price": 1000,
    "Comment":"work hard"
}

//delete order menu item
###
DELETE http://localhost:5000/api/order-menu-items/1

//.......................................................order_status...............................................................//

//get all order statuses
###
GET http://localhost:5000/api/order-statuses
Authorization: <your_token>

//get order status by Id
###
GET http://localhost:5000/api/order-statuses/1

//create order status
###
POST http://localhost:5000/api/order-statuses
content-type: application/json

{
    "Order_Id": 1,
    "Status_Catalog_Id": 1
}

//update order status
###
PUT http://localhost:5000/api/order-statuses/1
content-type: application/json

{
    "Order_Id": 1,
    "Status_Catalog_Id": 1
}

//delete order status
###
DELETE http://localhost:5000/api/order-statuses/1

//.......................................................orders...............................................................//

//get all orders
###
GET http://localhost:5000/api/orders
Authorization: <your_token>

//get order by Id
###
GET http://localhost:5000/api/orders/1

//create order
###
POST http://localhost:5000/api/orders
content-type: application/json

{
    "Restaurant_Id": 2,
    "Estimated_Delivery_Time": "2025-06-07T21:43:30.951Z",
    "Actual_Delivery_Time": "2025-06-07T21:43:30.951Z",
    "Delivery_Address_Id": 1,
    "User_Id": 1,
    "Driver_Id": 1,
    "Price": "500.00",
    "Discount": "50.00",
    "Final_Price": "450.00",
    "Comment": "Please deliver quickly"
}

//update order
###
PUT http://localhost:5000/api/orders/1
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "2023-09-15T12:00:00Z",
    "Actual_Delivery_Time": "2023-09-15T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 1,
    "Driver_Id": 1,
    "Price": 500,
    "Discount": 50,
    "Final_Price": 450,
    "Comment": "Please deliver quickly."
}

//delete order
###
DELETE http://localhost:5000/api/orders/1

//.......................................................  Restaurant Owner...............................................................//


//create  restaurant owners
###
POST http://localhost:5000/api/RestaurantOwner
content-type: application/json

{
    "Restaurant_Id": 1,
    "Owner_Id": 2

}

//get all restaurant owners
###
GET http://localhost:5000/api/RestaurantOwner
Authorization: <your_token>

//get restaurant owners with id
###
GET http://localhost:5000/api/RestaurantOwner/1


//update restaurant owner
###
PUT http://localhost:5000/api/RestaurantOwner/1
content-type: application/json

{
    "Restaurant_Id": 1,
    "Owner_Id": 1
}

//delete restaurant owner
###
DELETE http://localhost:5000/api/RestaurantOwner/15

//.......................................................comment...............................................................//

//get all comments
###
GET http://localhost:5000/api/comments
Authorization: <your_token>

//get comment by Id
###
GET http://localhost:5000/api/comments/1

//create comment
###
POST http://localhost:5000/api/comments
content-type: application/json

{
    "Order_Id": 1,
    "User_Id": 1,
    "Content": "Great service!"
}

//update comment
###
PUT http://localhost:5000/api/comments/1
content-type: application/json

{
    "Order_Id": 1,
    "User_Id": 1,
    "Content": "Excellent service!"
}

//delete comment
###
DELETE http://localhost:5000/api/comments/1


//......................................................./RestaurantOwner...............................................................//

//get all Restaurant Owners 
###
GET http://localhost:5000/api/RestaurantOwner
Authorization: <your_token>

//get Restaurant Owners  by Id
###
GET http://localhost:5000/api/RestaurantOwner/1

//create Restaurant Owners 
###
POST http://localhost:5000/api/RestaurantOwner
content-type: application/json

{
    "Restaurant_Id":1,
    "Owner_Id":2

}

//update Restaurant Owners 
###
PUT http://localhost:5000/api/RestaurantOwner/1
content-type: application/json

{
    "Restaurant_Id":1,
    "Owner_Id":2
}

//delete Restaurant Owners
###
DELETE http://localhost:5000/api/RestaurantOwner/1


//.......................................................status-catalogs...............................................................//

//get all status-catalogs
###
GET http://localhost:5000/api/status-catalogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiZGFuaWVsIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTA1NDkzMCwiaWF0IjoxNzQ5MDUxMzMwfQ.u5e51kHHu6DK-SDQ2Imi0gApMITH6dY-Mq3KNLAATCM

//get status-catalogs by Id
###
GET http://localhost:5000/api/status-catalogs/3

//create status-catalogs
###
POST http://localhost:5000/api/status-catalogs
content-type: application/json

{
    "Status_Catalog_Name":"bevarages"
}

//Update status-catalogs
###
PUT  http://localhost:5000/api/status-catalogs/1
content-type: application/json

{
    "Status_Catalog_Name":"bevarages"

}

//delete status-catalogs
###
DELETE http://localhost:5000/api/status-catalogs/2

@baseUrl = http://localhost:3000
@authToken = your_auth_token_here

### Orders Endpoints ###

### Get all orders
GET {{baseUrl}}/orders
Authorization: Bearer {{authToken}}

### Get order by ID
GET {{baseUrl}}/orders/1
Authorization: Bearer {{authToken}}

### Create a new order
POST {{baseUrl}}/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "today 11:30am",
    "Actual_Delivery_Time": "2025-06-09T11:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 35,
    "Driver_Id": 1,
    "Price": "500.0",
    "Discount": "20.5",
    "Final_Price": "485",
    "Comment": "Thank You",
    "items": [
        {
            "Menu_Item_Id": 1,
            "Quantity": 2,
            "Item_Price": "100",
            "Price": "150",
            "Comment": "Yummy"
        }
    ],
    "statuses": [
        {
            "Status_Catalog_Id": 1
        }
    ]
}

### Update an existing order
PUT {{baseUrl}}/orders/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "today 12:30pm",
    "Actual_Delivery_Time": "2025-06-09T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 35,
    "Driver_Id": 1,
    "Price": "550.0",
    "Discount": "25.5",
    "Final_Price": "525",
    "Comment": "Updated delivery instructions",
    "items": [
        {
            "Menu_Item_Id": 1,
            "Quantity": 3,
            "Item_Price": "100",
            "Price": "200",
            "Comment": "Extra spicy"
        }
    ],
    "statuses": [
        {
            "Status_Catalog_Id": 2
        }
    ]
}

### Delete an order
DELETE {{baseUrl}}/orders/1
Authorization: Bearer {{authToken}}

### Order Status Endpoints ###

### Get all order statuses
GET {{baseUrl}}/order-statuses
Authorization: Bearer {{authToken}}

### Get order status by ID
GET {{baseUrl}}/order-statuses/1
Authorization: Bearer {{authToken}}

### Create a new order status
POST {{baseUrl}}/order-statuses
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "Order_Id": 1,
    "Status_Catalog_Id": 1
}

### Delete an order status
DELETE {{baseUrl}}/order-statuses/1
Authorization: Bearer {{authToken}}

### Order Menu Items Endpoints ###

### Get all order menu items
GET {{baseUrl}}/order-menu-items
Authorization: Bearer {{authToken}}

### Get order menu item by ID
GET {{baseUrl}}/order-menu-items/1
Authorization: Bearer {{authToken}}

### Create a new order menu item
POST {{baseUrl}}/order-menu-items
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "Order_Id": 1,
    "Menu_Item_Id": 1,
    "Quantity": 2,
    "Special_Instructions": "Extra spicy"
}

### Update an order menu item
PUT {{baseUrl}}/order-menu-items/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "Order_Id": 1,
    "Menu_Item_Id": 1,
    "Quantity": 3,
    "Special_Instructions": "Medium spicy"
}

### Delete an order menu item
DELETE {{baseUrl}}/order-menu-items/1
Authorization: Bearer {{authToken}}
