//Default route
###
GET http://localhost:5000/



 //..........................................USER.......................................................//

//get all users
###
GET http://localhost:5000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiZGFuaWVsIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTA1NDkzMCwiaWF0IjoxNzQ5MDUxMzMwfQ.u5e51kHHu6DK-SDQ2Imi0gApMITH6dY-Mq3KNLAATCM


//get user by Id
###
GET http://localhost:5000/api/users/1

//register a user
###
POST http://localhost:5000/api/localhost:5000/api/auth/register
content-type: application/json

{
    "Full_Name": "daniel",
    "Contact_Phone": 1020,
    "Phone_Verified": false,
    "Email": "daniel@gmail.com",
    "Email_verified": false,
    "Confirmation_Code": "A1020",
    "Password": "daniel123",
    "User_Type": "member"
}

//login a user
###
POST http://localhost:5000/api/login
content-type: application/json

{ 
    "email":"Admin@gmail.com",
    "password":"Admin123"
    
}


//Update user
###
PUT  http://localhost:5000/api/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZnVsbE5hbWUiOiJhZG1pbiIsInVzZXJUeXBlIjoiYWRtaW4iLCJleHAiOjE3NDkwNTA5NjksImlhdCI6MTc0OTA0NzM2OX0.7zUvcqkawulbvmWhkC8VsuzxI7N8zn75TUbIiMuj5sc
content-type: application/json

{
   "Full_Name" : "Kaguru" ,
   "Contact_Phone" : 12345678 , 
  "Phone_Verified": false ,
   "Email" : "Kaguru@gmail.com" ,
   "Email_verified" : false , 
   "Confirmation_Code": "A123" ,
   "Password" : "Kaguru",
   "User_Type": "member"
    
}

//delete user
### 
DELETE http://localhost:5000/api/users/4
  


 // .......................................................state...............................................................//


 //get all states
###
GET http://localhost:5000/api/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZnVsbE5hbWUiOiJhZG1pbiIsInVzZXJUeXBlIjoiYWRtaW4iLCJleHAiOjE3NDkwNTA5NjksImlhdCI6MTc0OTA0NzM2OX0.7zUvcqkawulbvmWhkC8VsuzxI7N8zn75TUbIiMuj5sc


//get state by Id
###
GET http://localhost:5000/api/states/1
Authorization: 

//create state
###
POST http://localhost:5000/api/states
content-type: application/json
Authorization: 

{
    
    "State_Name": "Pumwani",
    "Code": "Nairobi 254"
    
}

//Update state
###
PUT  http://localhost:5000/api/states/1
content-type: application/json

{
    "State_Name": "Pumwani",
    "Code": "Nairobi 254"
}

//delete user
### 
DELETE http://localhost:5000/api/states/1
Authorization: 
  



//......................................................................CITY.........................................................................//


  //get all cities
###
GET http://localhost:5000/api/city
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZnVsbE5hbWUiOiJhZG1pbiIsInVzZXJUeXBlIjoiYWRtaW4iLCJleHAiOjE3NDkwNTA5NjksImlhdCI6MTc0OTA0NzM2OX0.7zUvcqkawulbvmWhkC8VsuzxI7N8zn75TUbIiMuj5sc


//get city by Id
###
GET http://localhost:5000/api/city/1

//create city
###
POST http://localhost:5000/api/city
content-type: application/json

{
    "City_Name": "Nai",
    "State_Id": 1  
}

//Update city
###
PUT  http://localhost:5000/api/city/1
content-type: application/json

{
    "City_Name": "Nai",
    "State_Id": 1
}

//delete city
### 
DELETE http://localhost:5000/api/city/1
  

  //......................................................................menu_Item.........................................................................//

//get all menu items
###
GET http://localhost:5000/api/menu_items
Authorization: <your_token>

//get menu item by Id  
### 
GET http://localhost:5000/api/menu_items/1

//create menu item
###
POST http://localhost:5000/api/menu_items
content-type: application/json

{
   "Menu_Item_Name": "Pizza",
   "Restaurant_Id": 1,
   "Category_Id": 500,
   "Description": "pizza.jpg",
   "Ingredients": 1,
   "Price": 500,
   "Active": true
}

//update menu item
###
PUT http://localhost:5000/api/menu_items/1
content-type: application/json

{
    "Menu_Item_Name": "Pizza",
    "Restaurant_Id": 1,
    "Category_Id": 500,
    "Description": "pizza.jpg",
    "Ingredients": 1,
    "Price": 500,
    "Active": true
}

//delete menu item
###
DELETE http://localhost:5000/api/menu_items/1

//.......................................................driver...............................................................//

//get all drivers
###
GET http://localhost:5000/api/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiZGFuaWVsIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTA1NDkzMCwiaWF0IjoxNzQ5MDUxMzMwfQ.u5e51kHHu6DK-SDQ2Imi0gApMITH6dY-Mq3KNLAATCM

//get driver by Id
###
GET http://localhost:5000/api/drivers/1

//create driver
###
POST http://localhost:5000/api/drivers
content-type: application/json

{
    "Car_Make": "Toyota",
    "Car_Model": "Corolla",
    "Car_Year": 2020,
    "User_Id": 1,
    "Online": true,
    "Delivering": false
}

//Update driver
###
PUT  http://localhost:5000/api/drivers/1
content-type: application/json

{
    "Car_Make": "Toyota",
    "Car_Model": "Corolla",
    "Car_Year": 2020,
    "User_Id": 1,
    "Online": true,
    "Delivering": false
}

//delete driver
###
DELETE http://localhost:5000/api/drivers/1

//.......................................................address...............................................................//

//get all addresses
###
GET http://localhost:5000/api/addresses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZGFuaWVsQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiZGFuaWVsIiwidXNlclR5cGUiOiJhZG1pbiIsImV4cCI6MTc0OTA1NDkzMCwiaWF0IjoxNzQ5MDUxMzMwfQ.u5e51kHHu6DK-SDQ2Imi0gApMITH6dY-Mq3KNLAATCM

//get address by Id
###
GET http://localhost:5000/api/addresses/1

//create address
###
POST http://localhost:5000/api/addresses
content-type: application/json

{
    "Street_Address_1": "123 Main St",
    "Street_Address_2": "Apt 4B",
    "Zip_Code": "10001",
    "Delivery_Instructions": "Leave at front door",
    "User_Id": 1,
    "City_Id": 1
}

//Update address
###
PUT  http://localhost:5000/api/addresses/1
content-type: application/json

{
    "Street_Address_1": "123 Main St",
    "Street_Address_2": "Apt 4B",
    "Zip_Code": "10001",
    "Delivery_Instructions": "Leave at front door",
    "User_Id": 1,
    "City_Id": 1
}

//delete address
###
DELETE http://localhost:5000/api/addresses/1


//.......................................................orders...............................................................//

//get all orders
###
GET http://localhost:5000/api/orders
Authorization: <your_token>

//get order by Id
###
GET http://localhost:5000/api/orders/1

//create order
###
POST http://localhost:5000/api/orders
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "2023-09-15T12:00:00Z",
    "Actual_Delivery_Time": "2023-09-15T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 1,
    "Driver_Id": 1,
    "Price": 500,
    "Discount": 50,
    "Final_Price": 450,
    "Comment": "Please deliver quickly."
}

//update order
###
PUT http://localhost:5000/api/orders/1
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "2023-09-15T12:00:00Z",
    "Actual_Delivery_Time": "2023-09-15T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 1,
    "Driver_Id": 1,
    "Price": 500,
    "Discount": 50,
    "Final_Price": 450,
    "Comment": "Please deliver quickly."
}

//delete order
###
DELETE http://localhost:5000/api/orders/1

//.......................................................order_menu...............................................................//

//get all order menu items
###
GET http://localhost:5000/api/order_menu
Authorization: <your_token>

//get order menu item by Id
###
GET http://localhost:5000/api/order_menu/1

//create order menu item
###
POST http://localhost:5000/api/order_menu
content-type: application/json

{
    "Order_Id": 1,
    "Menu_Item_Id": 1,
    "Quantity": 2,
    "Price": 1000
}

//update order menu item
###
PUT http://localhost:5000/api/order_menu/1
content-type: application/json

{
    "Order_Id": 1,
    "Menu_Item_Id": 1,
    "Quantity": 2,
    "Price": 1000
}

//delete order menu item
###
DELETE http://localhost:5000/api/order_menu/1

//.......................................................order_status...............................................................//

//get all order statuses
###
GET http://localhost:5000/api/order_status
Authorization: <your_token>

//get order status by Id
###
GET http://localhost:5000/api/order_status/1

//create order status
###
POST http://localhost:5000/api/order_status
content-type: application/json

{
    "Order_Id": 1,
    "Status_Catalog_Id": 1
}

//update order status
###
PUT http://localhost:5000/api/order_status/1
content-type: application/json

{
    "Order_Id": 1,
    "Status_Catalog_Id": 1
}

//delete order status
###
DELETE http://localhost:5000/api/order_status/1

//.......................................................orders...............................................................//

//get all orders
###
GET http://localhost:5000/api/orders
Authorization: <your_token>

//get order by Id
###
GET http://localhost:5000/api/orders/1

//create order
###
POST http://localhost:5000/api/orders
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "2023-09-15T12:00:00Z",
    "Actual_Delivery_Time": "2023-09-15T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 1,
    "Driver_Id": 1,
    "Price": 500,
    "Discount": 50,
    "Final_Price": 450,
    "Comment": "Please deliver quickly."
}

//update order
###
PUT http://localhost:5000/api/orders/1
content-type: application/json

{
    "Restaurant_Id": 1,
    "Estimated_Delivery_Time": "2023-09-15T12:00:00Z",
    "Actual_Delivery_Time": "2023-09-15T12:30:00Z",
    "Delivery_Address_Id": 1,
    "User_Id": 1,
    "Driver_Id": 1,
    "Price": 500,
    "Discount": 50,
    "Final_Price": 450,
    "Comment": "Please deliver quickly."
}

//delete order
###
DELETE http://localhost:5000/api/orders/1

//......................................................./RestaurantOwner...............................................................//

//get all status 
###
GET http://localhost:5000/api//RestaurantOwner
Authorization: <your_token>

//get status catalog by Id
###
GET http://localhost:5000/api//RestaurantOwner/1

//create status catalog
###
POST http://localhost:5000/api//RestaurantOwner
content-type: application/json

{
    "Name": "In Progress"
}

//update status catalog
###
PUT http://localhost:5000/api//RestaurantOwner/1
content-type: application/json

{
    "Name": "Completed"
}

//delete status catalog
###
DELETE http://localhost:5000/api//RestaurantOwner/1

//.......................................................comment...............................................................//

//get all comments
###
GET http://localhost:5000/api/comments
Authorization: <your_token>

//get comment by Id
###
GET http://localhost:5000/api/comments/1

//create comment
###
POST http://localhost:5000/api/comments
content-type: application/json

{
    "Order_Id": 1,
    "User_Id": 1,
    "Content": "Great service!"
}

//update comment
###
PUT http://localhost:5000/api/comments/1
content-type: application/json

{
    "Order_Id": 1,
    "User_Id": 1,
    "Content": "Excellent service!"
}

//delete comment
###
DELETE http://localhost:5000/api/comments/1


//......................................................./RestaurantOwner...............................................................//

//get all Restaurant Owners 
###
GET http://localhost:5000/api/RestaurantOwner
Authorization: <your_token>

//get Restaurant Owners  by Id
###
GET http://localhost:5000/api/RestaurantOwner/1

//create Restaurant Owners 
###
POST http://localhost:5000/api/RestaurantOwner
content-type: application/json

{
    "Restaurant_Id":1,
    "Owner_Id":2

}

//update Restaurant Owners 
###
PUT http://localhost:5000/api/RestaurantOwner/1
content-type: application/json

{
    "Restaurant_Id":1,
    "Owner_Id":2
}

//delete Restaurant Owners catalog
###
DELETE http://localhost:5000/api/RestaurantOwner/1
